# Generated by Django 5.1 on 2024-08-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("img", models.ImageField(upload_to="")),
                ("bio", models.TextField()),
                ("roles", models.TextField()),
                ("pronouns", models.CharField(max_length=255)),
                ("major", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("fact", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "authors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vol", models.IntegerField(default=0)),
                ("num", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "issues",
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("alt_text", models.CharField(max_length=255)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="articles.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(related_name="articles", to="articles.author"),
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                related_name="articles", to="articles.category"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=60)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="issues",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="articles.issue",
            ),
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(max_length=255, verbose_name="link destination"),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="link text"
                    ),
                ),
                (
                    "issues",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc_links",
                        to="articles.author",
                    ),
                ),
            ],
        ),
    ]
