# Generated by Django 5.1 on 2024-08-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="author",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="author",
            name="pronouns",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="author",
            name="roles",
            field=models.CharField(max_length=1024),
        ),
    ]
