# Generated by Django 5.1 on 2024-09-23 15:52

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["pk"], "verbose_name_plural": "authors"},
        ),
        migrations.AddField(
            model_name="issue",
            name="archive",
            field=models.FileField(
                default="TEMP_ARTICLE_PDF_STRING",
                upload_to=articles.models.issue_upload_path,
            ),
            preserve_default=False,
        ),
    ]
