# Generated by Django 5.1 on 2024-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_author_email_alter_author_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(upload_to="media/static"),
        ),
    ]
