# Generated by Django 5.1 on 2024-09-23 18:14

import articles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_author_options_issue_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="archive",
            field=models.FileField(
                upload_to=articles.models.issue_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
