# Generated by Django 5.1 on 2024-08-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_articleimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(upload_to="articles/static/author_images"),
        ),
    ]
