# Generated by Django 5.1 on 2024-08-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_articleimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(upload_to="articles/static/article_images"),
        ),
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(upload_to="articles/static/author_images"),
        ),
    ]
