# Generated by Django 5.1 on 2024-08-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0005_alter_articleimage_alt_text_alter_articleimage_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(upload_to="article_images/"),
        ),
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(upload_to="author_images/"),
        ),
    ]
