# Generated by Django 5.1 on 2025-01-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_issue_release_date_alter_author_author_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="issues",
            new_name="issue",
        ),
    ]
