# Generated by Django 5.1 on 2025-01-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_issue_release_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="created_on",
        ),
    ]
