# Generated by Django 5.1 on 2025-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_remove_article_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_on",
            field=models.DateField(
                blank=True,
                help_text="The date for an article defaults to its issue's date. You can also set it here to override this default.",
                null=True,
            ),
        ),
    ]
