# Generated by Django 5.1 on 2025-01-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_article_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="true_created_on",
            field=models.DateField(
                blank=True,
                help_text="field hidden from admin panel. can be updated when this Article or its corresponding Issue is updated. should prefer Article's date, falling back to Issue if it was NULL.",
                null=True,
            ),
        ),
    ]
