# Generated by Django 5.1 on 2025-01-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_article_true_created_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={
                "ordering": ["vol", "num", "name"],
                "verbose_name_plural": "issues",
            },
        ),
    ]
