# Generated by Django 5.1 on 2025-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_issue_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='DONT add the words paid for: just add the gag bit thx <3', max_length=225)),
            ],
        ),
    ]
