# Generated by Django 5.1 on 2025-02-04 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_paidfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_issue', to='articles.issue')),
            ],
        ),
    ]
