# Generated by Django 5.1 on 2025-03-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_rejectedheadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexpage",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
