# Generated by Django 5.1 on 2025-04-08 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_indexpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, help_text='If we want this article to have a higher chance of being featured'),
        ),
        migrations.AddField(
            model_name='article',
            name='front_page',
            field=models.BooleanField(default=False, help_text='If this article was on the front page of the issue in which it was published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.issue'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='issues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misc_links', to='articles.author'),
        ),
    ]
