# Generated by Django 5.1 on 2025-04-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_featured_article_front_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['issue__name', 'front_page', 'featured']},
        ),
    ]
