# Generated by Django 5.1 on 2025-04-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['issue__vol', 'issue__num', 'front_page', 'featured', 'slug']},
        ),
    ]
