# Generated by Django 5.1 on 2025-04-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectedheadline',
            options={'ordering': ['issue__vol', 'issue__num', 'title']},
        ),
    ]
