# Generated by Django 5.1 on 2025-04-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectedheadline',
            options={},
        ),
    ]
