# Generated by Django 5.1 on 2025-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_rejectedheadline_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='paidfor',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
