# Generated by Django 5.1 on 2025-10-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_category_options_alter_paidfor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='rejectedheadline',
            name='featured',
            field=models.BooleanField(default=False, help_text='If this rejected headline is really funny and we want it to have a high chance of being on the front page ticker'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
