# Generated by Django 5.1 on 2025-10-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_remove_article_categories_rejectedheadline_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='issues',
            new_name='author',
        ),
    ]
