# Generated by Django 5.1 on 2025-10-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_rename_issues_socialmedialink_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
