# Generated by Django 5.1 on 2025-10-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexPage',
        ),
    ]
