# Generated by Django 5.1 on 2025-10-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_delete_indexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(default='/static/anon.png', upload_to='author_images/'),
        ),
    ]
