# Generated by Django 5.1 on 2025-10-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_alter_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
    ]
