# Generated by Django 5.1 on 2025-10-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_alter_author_options_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='author',
            name='fact',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='author',
            name='major',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='pronouns',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='author',
            name='year',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paidfor',
            name='title',
            field=models.CharField(help_text='DONT add the words paid for: just add the gag bit thx <3', max_length=1024),
        ),
        migrations.AlterField(
            model_name='rejectedheadline',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
