# Generated by Django 5.1 on 2025-10-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_alter_article_title_alter_articleimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='This uses markdown formating. If you want to have an image in an article you add one like this {{imagename.fileextension}}'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='The slug is in the url like this: cmureadme.com/articles/slug use dashes as spaces example-slug-like-this', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(help_text='This uses markdown formating'),
        ),
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, help_text='Default image is set to the anon.png its better for everyone to have a pfp, but if you are waiting on someone to send one this is a good short term option', null=True, upload_to='author_images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='roles',
            field=models.CharField(default='Staffwriter', help_text='Defaults to Staffwriter, change this to Staff Artist if someone only makes images. Can also add exec roles for exec members or other funny roles if people want', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paidfor',
            name='title',
            field=models.CharField(help_text='DONT add the words paid for by: just add the gag bit thx <3', max_length=1024),
        ),
    ]
