# Generated by Django 5.1 on 2025-10-13 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_alter_article_body_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='release_date',
            field=models.DateField(default=datetime.date.today, help_text='Defaults to the current day, change this if the issue was not published the same day you are uploading'),
        ),
    ]
