# Generated by Django 5.1 on 2025-11-07 04:31

import datetime
import django.core.validators
import django.db.models.deletion
import magazine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('body', models.TextField(help_text='This uses markdown formating. If you want to have an image in an article you add one like this {{imagename.fileextension}}')),
                ('created_on', models.DateField(blank=True, help_text="The date for an article defaults to its issue's date. You can also set it here to override this default.", null=True)),
                ('true_created_on', models.DateField(blank=True, help_text="field hidden from admin panel. can be updated when this Article or its corresponding Issue is updated. should prefer Article's date, falling back to Issue if it was NULL.", null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='The slug is in the url like this: cmureadme.com/articles/slug use dashes as spaces example-slug-like-this', unique=True)),
                ('front_page', models.BooleanField(default=False, help_text='If this article was on the front page of the issue in which it was published')),
                ('featured', models.BooleanField(default=False, help_text='If we want this article to have a higher chance of being featured')),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['issue__vol', 'issue__num', '-front_page', '-featured', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('img', models.ImageField(blank=True, help_text='Default image is set to the anon.png its better for everyone to have a pfp, but if you are waiting on someone to send one this is a good short term option', null=True, upload_to='author_images/')),
                ('bio', models.TextField(help_text='This uses markdown formating')),
                ('roles', models.CharField(default='Staffwriter', help_text='Defaults to Staffwriter, change this to Staff Artist if someone only makes images. Can also add exec roles for exec members or other funny roles if people want', max_length=1024)),
                ('pronouns', models.CharField(blank=True, max_length=1024)),
                ('major', models.CharField(max_length=1024)),
                ('year', models.CharField(max_length=1024)),
                ('location', models.CharField(blank=True, max_length=1024)),
                ('fact', models.CharField(max_length=1024)),
                ('email', models.CharField(blank=True, max_length=1024)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author_status', models.CharField(choices=[('US', 'Usual Suspect'), ('IC', 'Independent Contractor'), ('EE', 'Escapee')], default='US', help_text='Usual suspect for current writers or recurring characters, independent contractors for one off bits, escapee for alumni', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('vol', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0)),
                ('archive', models.FileField(upload_to=magazine.models.issue_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('release_date', models.DateField(default=datetime.date.today, help_text='Defaults to the current day, change this if the issue was not published the same day you are uploading')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'issues',
                'ordering': ['vol', 'num', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaidFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='DONT add the words paid for by: just add the gag bit thx <3', max_length=1024)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=magazine.models.article_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=1024)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='magazine.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='magazine.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='magazine.issue'),
        ),
        migrations.CreateModel(
            name='RejectedHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('featured', models.BooleanField(default=False, help_text='If this rejected headline is really funny and we want it to have a high chance of being on the front page ticker')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_issue', to='magazine.issue')),
            ],
            options={
                'ordering': ['issue__vol', 'issue__num'],
            },
        ),
    ]
