# Generated by Django 5.2.7 on 2025-11-13 01:35

from django.db import migrations, models
from django.apps.registry import Apps
import re

def choose_slugs(apps: Apps, schema_editor):
    Author = apps.get_model("magazine", "Author")

    slugs = set()
    
    for obj in Author.objects.all():
        slug = re.sub('[^a-zA-Z0-9]+', '-', re.sub('(^[^a-zA-Z0-9]+)|([^a-zA-Z0-9]+$)', '', obj.name)).lower()

        while slug in slugs:
            slug += '-'

        obj.slug = slug

        obj.save()

def unchoose_slugs(apps: Apps, schema_editor):
    Author = apps.get_model("magazine", "Author")
    
    for obj in Author.objects:
        obj.slug = None

class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(
            code=choose_slugs,
            reverse_code=unchoose_slugs
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        )
    ]
