# Generated by Django 5.2.9 on 2025-12-10 01:00

from django.apps.registry import Apps
from django.db import migrations, models


def blankify_left_empties(apps: Apps, schema_editor):
    Author = apps.get_model("magazine", "Author")

    for obj in Author.objects.all():
        if obj.bio.strip().lower() == "left_empty":
            obj.bio = ""
        if obj.fact.strip().lower() == "left_empty":
            obj.fact = ""
        if obj.pronouns.strip().lower() == "left_empty":
            obj.pronouns = ""
        if obj.location.strip().lower() == "left_empty":
            obj.location = ""
        if obj.email.strip().lower() == "left_empty":
            obj.email = ""
        if obj.major.strip().lower() == "left_empty":
            obj.major = ""
        if obj.year.strip().lower() == "left_empty":
            obj.year = ""

        obj.save()


def left_emptyify_blanks(apps: Apps, schema_editor):
    Author = apps.get_model("magazine", "Author")

    for obj in Author.objects.all():
        if obj.bio == "":
            obj.bio = "left_empty"
        if obj.fact == "":
            obj.fact = "left_empty"
        if obj.major == "":
            obj.major = "left_empty"
        if obj.roles == "":
            obj.roles = "Staffwriter"
        if obj.year == "":
            obj.year = "left_empty"

        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0003_author_alias_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True, help_text="This uses markdown formating"),
        ),
        migrations.AlterField(
            model_name="author",
            name="fact",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="author",
            name="major",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="author",
            name="roles",
            field=models.CharField(
                blank=True,
                default="Staffwriter",
                help_text="Defaults to Staffwriter, change this to Staff Artist if someone only makes images. Can also add exec roles for exec members or other funny roles if people want",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="year",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.RunPython(code=blankify_left_empties, reverse_code=left_emptyify_blanks),
    ]
