# Generated by Django 5.2.9 on 2025-12-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_alter_author_bio_alter_author_fact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anon_authors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='articles', to='magazine.author'),
        ),
    ]
