# Generated by Django 6.0 on 2025-12-17 23:23

import django.db.models.deletion
import magazine.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0006_article_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anon_artists", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to=magazine.models.image_gag_upload_path)),
                ("alt_text", models.CharField(blank=True, max_length=1024)),
                ("caption", models.TextField(blank=True)),
                (
                    "created_on",
                    models.DateField(
                        blank=True,
                        help_text="The date for an article defaults to its issue's date. You can also set it here to override this default.",
                        null=True,
                    ),
                ),
                (
                    "true_created_on",
                    models.DateField(
                        blank=True,
                        help_text="field hidden from admin panel. can be updated when this Article or its corresponding Issue is updated. should prefer Article's date, falling back to Issue if it was NULL.",
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug is in the url like this: cmureadme.com/articles/slug use dashes as spaces example-slug-like-this",
                        unique=True,
                    ),
                ),
                (
                    "front_page",
                    models.BooleanField(
                        default=False,
                        help_text="If this article was on the front page of the issue in which it was published",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="If we want this article to have a higher chance of being featured"
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                ("artists", models.ManyToManyField(blank=True, related_name="image_gags", to="magazine.author")),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="image_gags", to="magazine.issue"
                    ),
                ),
            ],
            options={
                "ordering": ["issue__vol", "issue__num", "-front_page", "-featured", "slug"],
            },
        ),
    ]
