# Generated by Django 5.1 on 2025-12-21 20:24

import django.core.validators
import magazine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_imagegag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='This uses markdown formatting. If you want to have an image in an article you add one like this ![](imagename.fileextension)'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text="This is what screen readers and other accessability tools use. Include a description of what's going on in the image.", max_length=1024),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(help_text="Upload the image here. Name it something useful since you have to type out it's exact name when you embed it in the article body.", upload_to=magazine.models.article_image_upload_path),
        ),
        migrations.AlterField(
            model_name='imagegag',
            name='alt_text',
            field=models.CharField(blank=True, help_text="This is what screen readers and other accessability tools use. Include a description of what's going on in the image.", max_length=1024),
        ),
        migrations.AlterField(
            model_name='imagegag',
            name='caption',
            field=models.TextField(blank=True, help_text='This uses markdown formatting.'),
        ),
        migrations.AlterField(
            model_name='imagegag',
            name='created_on',
            field=models.DateField(blank=True, help_text="The date for an image defaults to its issue's date. You can also set it here to override this default.", null=True),
        ),
        migrations.AlterField(
            model_name='imagegag',
            name='slug',
            field=models.SlugField(help_text='The slug is in the url like this: cmureadme.com/image/slug use dashes as spaces example-slug-like-this', unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='archive',
            field=models.FileField(help_text="Upload the pdf here. Don't worry about naming it, the file gets auto renamed on upload.", upload_to=magazine.models.issue_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
