# Generated by Django 6.0 on 2025-12-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0008_alter_article_body_alter_articleimage_alt_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_on",
            field=models.DateField(
                blank=True,
                help_text="Defaults to the issue date. You can set it here to override this default.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="If we want this to have a higher chance of being featured"
            ),
        ),
        migrations.AlterField(
            model_name="imagegag",
            name="created_on",
            field=models.DateField(
                blank=True,
                help_text="Defaults to the issue date. You can set it here to override this default.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="imagegag",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="If we want this to have a higher chance of being featured"
            ),
        ),
        migrations.AlterField(
            model_name="imagegag",
            name="front_page",
            field=models.BooleanField(
                default=False,
                help_text="If this image gag was on the front page of the issue in which it was published",
            ),
        ),
    ]
