# Generated by Django 5.1 on 2026-03-13 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0011_alter_issue_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="paid_for",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="paid_for", to="magazine.paidfor"
            ),
        ),
    ]
