# Generated by Django 5.1 on 2026-03-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0012_issue_paid_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='free',
            field=models.CharField(help_text='This is what goes before : Free', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='three_dollars',
            field=models.CharField(help_text='This is what goes before : $3', max_length=1024, null=True),
        ),
    ]
