# Generated by Django 5.1 on 2026-05-01 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0013_issue_free_issue_three_dollars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='magazine.issue'),
        ),
        migrations.AlterField(
            model_name='imagegag',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_gags', to='magazine.issue'),
        ),
    ]
