# Generated by Django 6.0.5 on 2026-05-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0014_authoradminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegag',
            name='title',
            field=models.CharField(default='Title', help_text='Title of the image', max_length=1024),
            preserve_default=False,
        ),
    ]
