# Generated by Django 6.0.5 on 2026-05-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0015_imagegag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
