# Generated by Django 6.0.5 on 2026-07-22 06:59

import magazine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_article_byline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, help_text='Default image is set to the anon.png its better for everyone to have a pfp, but if you are waiting on someone to send one this is a good short term option', null=True, upload_to=magazine.models.author_image_upload_path),
        ),
    ]
