# Generated by Django 6.0.5 on 2026-08-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0017_alter_author_img'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('vol', 'num'), name='unique_issue_vol_num'),
        ),
    ]
