# Generated by Django 6.0.5 on 2026-08-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0018_issue_unique_issue_vol_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline_italic',
            field=models.BooleanField(default=True, help_text='Uncheck to disable the default italic styling on the byline.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, help_text='This uses markdown formatting, doing nothing will have the byline italicized like in print.', max_length=1024),
        ),
    ]
